export ZSH="/home/jacob/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh
alias ls='ls -h --group-directories-first --color'
alias ll='ls -lah --group-directories-first  --color'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

alias vz='vim ~/.zshrc'
alias dbx='cd /opt/devilbox; sudo service mysql stop; sudo service nginx stop; sudo service docker start; sudo docker-compose up'
export DOTNET_CLI_TELEMETRY_OPTOUT=1
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
export DISABLE_AUTO_TITLE=true
ls -ld /home/jacob/.adobe /home/jacob/.android /home/jacob/.AndroidStudio3.2 /home/jacob/.aspnet /home/jacob/.cache /home/jacob/.calcurse /home/jacob/.cargo /home/jacob/.cfg /home/jacob/.composer /home/jacob/.config /home/jacob/.configbak /home/jacob/.cpan /home/jacob/.dbus /home/jacob/.dircolors /home/jacob/.dmenurc /home/jacob/.dmrc /home/jacob/.dotfiles /home/jacob/.dotnet /home/jacob/.editorconfig /home/jacob/.fehbg /home/jacob/.fonts.conf /home/jacob/.fzf /home/jacob/.fzf.bash /home/jacob/.fzf.zsh /home/jacob/.gconf /home/jacob/.gem /home/jacob/.gitconfig /home/jacob/.gitignore /home/jacob/.gnome /home/jacob/.gnome2 /home/jacob/.gnome2_private /home/jacob/.gnome-commander /home/jacob/.gnupg /home/jacob/.gphoto /home/jacob/.gtkrc-2.0 /home/jacob/.gvfs /home/jacob/.hardinfo /home/jacob/.history /home/jacob/.ICEauthority /home/jacob/.icons /home/jacob/.java /home/jacob/.kde /home/jacob/.lastpass /home/jacob/.lesshst /home/jacob/.local /home/jacob/.macromedia /home/jacob/.mono /home/jacob/.mozilla /home/jacob/.mutt /home/jacob/.muttrc /home/jacob/.mysql /home/jacob/.netrc /home/jacob/.node-gyp /home/jacob/.npm /home/jacob/.nuget /home/jacob/.nvm /home/jacob/.oh-my-zsh /home/jacob/.phpls /home/jacob/.pki /home/jacob/.profile /home/jacob/.rpmdb /home/jacob/.rtorrent.rc /home/jacob/.selected_editor /home/jacob/.sqlite_history /home/jacob/.ssh /home/jacob/.sudo_as_admin_successful /home/jacob/.templateengine /home/jacob/.thumbnails /home/jacob/.thunderbird /home/jacob/.tldr /home/jacob/.tmux.conf /home/jacob/.tmuxinator /home/jacob/.tmuxp /home/jacob/.todos /home/jacob/.torrents_incomplete /home/jacob/.vim /home/jacob/.viminfo /home/jacob/.vimrc /home/jacob/.vmail /home/jacob/.vmailrc /home/jacob/.vscode /home/jacob/.wget-hsts /home/jacob/.Xauthority /home/jacob/.xinitrc /home/jacob/.Xresources /home/jacob/.xsession-errors /home/jacob/.xtend.Xresources.DISABLED /home/jacob/.yarnrc /home/jacob/.zcompdump /home/jacob/.zcompdump-lap-5.4.2 /home/jacob/.zsh_history /home/jacob/.zshrc /home/jacob/.zshrc.pre-oh-my-zsh
ls -ld /home/jacob/.adobe /home/jacob/.android /home/jacob/.AndroidStudio3.2 /home/jacob/.aspnet /home/jacob/.cache /home/jacob/.calcurse /home/jacob/.cargo /home/jacob/.cfg /home/jacob/.composer /home/jacob/.config /home/jacob/.configbak /home/jacob/.cpan /home/jacob/.dbus /home/jacob/.dircolors /home/jacob/.dmenurc /home/jacob/.dmrc /home/jacob/.dotfiles /home/jacob/.dotnet /home/jacob/.editorconfig /home/jacob/.fehbg /home/jacob/.fonts.conf /home/jacob/.fzf /home/jacob/.fzf.bash /home/jacob/.fzf.zsh /home/jacob/.gconf /home/jacob/.gem /home/jacob/.gitconfig /home/jacob/.gitignore /home/jacob/.gnome /home/jacob/.gnome2 /home/jacob/.gnome2_private /home/jacob/.gnome-commander /home/jacob/.gnupg /home/jacob/.gphoto /home/jacob/.gtkrc-2.0 /home/jacob/.gvfs /home/jacob/.hardinfo /home/jacob/.history /home/jacob/.ICEauthority /home/jacob/.icons /home/jacob/.java /home/jacob/.kde /home/jacob/.lastpass /home/jacob/.lesshst /home/jacob/.local /home/jacob/.macromedia /home/jacob/.mono /home/jacob/.mozilla /home/jacob/.mutt /home/jacob/.muttrc /home/jacob/.mysql /home/jacob/.netrc /home/jacob/.node-gyp /home/jacob/.npm /home/jacob/.nuget /home/jacob/.nvm /home/jacob/.oh-my-zsh /home/jacob/.phpls /home/jacob/.pki /home/jacob/.profile /home/jacob/.rpmdb /home/jacob/.rtorrent.rc /home/jacob/.selected_editor /home/jacob/.sqlite_history /home/jacob/.ssh /home/jacob/.sudo_as_admin_successful /home/jacob/.templateengine /home/jacob/.thumbnails /home/jacob/.thunderbird /home/jacob/.tldr /home/jacob/.tmux.conf /home/jacob/.tmuxinator /home/jacob/.tmuxp /home/jacob/.todos /home/jacob/.torrents_incomplete /home/jacob/.vim /home/jacob/.viminfo /home/jacob/.vimrc /home/jacob/.vmail /home/jacob/.vmailrc /home/jacob/.vscode /home/jacob/.wget-hsts /home/jacob/.Xauthority /home/jacob/.xinitrc /home/jacob/.Xresources /home/jacob/.xsession-errors /home/jacob/.xtend.Xresources.DISABLED /home/jacob/.yarnrc /home/jacob/.zcompdump /home/jacob/.zcompdump-lap-5.4.2 /home/jacob/.zsh_history /home/jacob/.zshrc /home/jacob/.zshrc.pre-oh-my-zsh
